led:
  amount: 300
  bar-amount: 5
  bar-length: 60
  spacer-length: 0
  flip: true

audio:
  device-index: auto
  channels: 2
  rate: 44100
  chunk-size: 2048
  min-freq: 32
  max-freq: 16000

viz:
  decay: 0.965
  colors:
    tick_per_led: 0
    tick_per_time: 1
    tick_per_column: 0
    active-mode: static
    modes:
      static:
        r: 0
        g: 0
        b: 255
      rainbow:
        rate: 0.01
        lightness: 0.5
        saturation: 1
      fade:
        - - 255
          - 0
          - 0
        - - 0
          - 255
          - 0
        - - 0
          - 0
          - 255
