led:
  amount: 300
  bar-amount: 5
  bar-length: 60
  spacer-length: 0
  flip: false

audio:
  device-index: auto
  channels: 2
  rate: 44100
  chunk-size: 2048
  min-freq: 32
  max-freq: 16000

viz:
  decay: 0.965
  colors:
    active-mode: strength
    modes:
      static:
        r: 0
        g: 0
        b: 255
      strength:
        low: 0.472
        high: 0.777
        saturation: 1
        value: 1
      rainbow:
        rate: 0.01
        lightness: 0.5
        saturation: 1
