led:
  amount: 160
  bar-amount: 10
  bar-length: 12
  spacer-length: 4

audio:
  device-index: 1
  channels: 2
  rate: 44100
  chunk-size: 1024
  min-freq: 150
  max-freq: 20000

viz:
  decay: 0.8
  colors:
    tick_per_led: 0
    tick_per_time: 1
    tick_per_column: 0
    active-mode: static
    modes:
      static:
        r: 0
        g: 255
        b: 0
      rainbow:
        rate: 0.01
        lightness: 0.5
        saturation: 1
      fade:
        - - 255
          - 0
          - 0
        - - 0
          - 255
          - 0
        - - 0
          - 0
          - 255
